### PR TITLE
OOP - Milestone: Repository Setup - PR For Review

### PR DESCRIPTION
**Pull request by udberg**
This is the initial repository setup for our (@udberg and @taiwo2) tic-tac-toe game built as part of the OOP in the Ruby Module of the Technical Curriculum. In this setup, we included
- lib with a .gitkeep file for the game logic
- bin - with the [executable file] https://commandercoriander.net/blog/2013/02/16/making-a-ruby-script-executable/) called main.rb.
- main.rb file responsible for user interaction. This is the only place where puts and get.chomp can be used.

### CODE REVIEW

**Comment by descholar-ceo** [comment]
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: 
## Please wait a bit ...

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @taiwo2 and @udberg  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [x] The previous reviewer requested that you should open a pull request which points from the feature branch to the `develop` branch. :point_right: That change is not implemented yet. Currently your Pull Request is pointing to the master branch. That is violating git/github flow we use, kindly fix that before you submit another code review request.
=> [Screenshot from the pathwright](https://user-images.githubusercontent.com/58504655/103526433-bac3e180-4ea2-11eb-845b-345530becfb5.png)
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by udberg** [comment]
> # Status: Changes Required 🚦 ⚠️
> ## Hello @taiwo2 and @udberg 🤝 🤝 🤝
> 👍 This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
> 👍 I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
> 
> #### ⚠️ However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below 👇 👇 👇
> ### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding
> # [Required Changes] 🔴
> * [x]  The previous reviewer requested that you should open a pull request which points from the feature branch to the `develop` branch. 👉 That change is not implemented yet. Currently your Pull Request is pointing to the master branch. That is violating git/github flow we use, kindly fix that before you submit another code review request.
>   => [Screenshot from the pathwright](https://user-images.githubusercontent.com/58504655/103526433-bac3e180-4ea2-11eb-845b-345530becfb5.png)
> 
> _If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._
> 
> [GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)
> 
> _Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

hello @descholar-ceo . Thank you for the review but I am utterly confused with the. changes you're requesting. We had to close the first PR because we hadn't created a "development" branch and we were trying to merge into master, which is what the previous TSE pointed out and which prompted us to start all over again. We have a setup branch and a development branch which we're now trying to merge , which makes your request rather confusing. We'd love to know exactly what we're doing wrong as that could help us progress to the next stage.
Thank you,
@udberg  and @taiwo2 .

**Review by PhillipUg — APPROVED** [review]
# Status: Project Approved! 🥇 
Congratulations on implementing all requirements and getting this milestone approved. :+1:

You can merge this branch into the development branch when you're ready and go on to your next milestone.
:bulb:  Do not forget to submit your project completion form after merging this branch.

All the best team,

For any assistance, you can contact me on slack as **Phillip Musiime**

**Pull request merged**
