### PR TITLE
OOP - Milestone: User Interface - PR For Review

### PR DESCRIPTION
**Pull request by udberg**
In this project, we (@udberg and @taiwo2) created a main.rb file responsible for user interaction and which takes in the following
- the steps needed to play the game
- what is needed from players
- what we need to display for the players
- general rules and requirements to play tic-tac-toe.

### CODE REVIEW

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @udberg  & @taiwo2**

---
### Requested 🔴 

- [x] I just need to understand one thing, why did you delete the main file content?
       in this milestone you are supposed to do all of what you did in the main file, but in the 
       readme file.
       please reverse your changes to the main file do that the game actually works.

---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Comment by taiwo2** [comment]
kindly check the main file. Nothing was deleted, we only delete unnecessary content. check it, all required to-do list was stated there.

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
- [x] you are supposed to add the instructions to the readme file of the project that was approved in the last milestone. not to delete all of its content and add instructions.
- [x] please reverse all that you have done since the last milestone was approved and add the instructions to the readme file.


please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Review by ebeagusamuel — CHANGES_REQUESTED** [review]
# Changes Required :recycle: 
### Hey there,
##### You haven't followed the specification for this milestone. In this milestone, you are required to mock the flow of the game, i.e how the game would flow and you are expected to do this without actually implementing any logic. What you have done is just to write out steps/ pseudocode and not actually implementing those pseudocode. I will try to list out all you need to do for this milestone below.
- [x] Your game tells which player turn it is (without computing who the winner is).
- [x] Your game asks the player to select from available moves.
- [x] Your game informs the player if the selected move is invalid (without computing what an invalid move is).
- [x] Your game displays board after the player move (without computing which spots on the board are taken).
- [x] Your game informs player if the selected move is a winning move (without computing the winning move).
- [x] Your game informs player if the selected move is a draw move (without computing draw).
- [x] Your game repeats all actions for the next player's move.

#### Please update your game and request another review when you are done.
slack(@ebeagusamuel)

**Comment by arslanbisharat** [comment]
### This Pull Request is Under Review.

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Request changes 😳

I am very happy to see this project and I can see you worked hard on this project. There are only a few issues that we need to address and I am sure that you will end up with a perfect project

_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_

This is a great opportunity to learn. Microverse is here to help you. 

**Please have a look at the suggestions to get more understanding.**

- [x] At the end of your main.rb file, you have an extra **end** tag. Please remove that tag. That tag is stopping the file to execute. 
**Pro Tip** Always run your project in localhost before requestingfor a review. 
## Behaviour

- [x] In this step you are supposed to only **mock** the basic flow of the game. This means implementing a user interface that displays prompts for users (print/puts) and collects user input (`gets.chomp`). No game logic (for example checking who is a winner) is required in this milestone - instead, you can just display "The winner is X" no matter who won. Usage of inline comments in this milestone is allowed. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
- [x] Basic game flow is prepared: ([screenshot hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
  - [x] `[REQUIRED]` game tells which player turn it is (without computing who the winner is)
  - [x] `[REQUIRED]` game asks the player to select from available moves
  - [x] `[REQUIRED]` game informs player if the selected move is invalid (without computing what an invalid move is)
  - [x] `[REQUIRED]` game displays board after the player move (without computing which spots on the board are taken)
  - [x] `[REQUIRED]` game informs player if the selected move is a winning move (without computing the winning move)
  - [x] `[REQUIRED]` game informs player if the selected move is a draw move (without computing draw)
  - [x] `[REQUIRED]` game repeats all actions for the next player's move

  **But your game gives an error after the first move**

## Implementation details

- [x] A loop is needed in this game (recommended is `while` but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))
- [x] Inside the loop, you should call actions repeated for each move
- [x] A loop needs to be terminated at some point (after a winning move or draw to be more specific). It can be done with variable:

```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move

  if winner # and/or draw (the exact condition in this milestone is not important)
 game_on = false
  end
end
```

- [x] Using out-of-nowhere numbers to terminate a loop, for example, `5.times do ... end` is a signal that something is wrong. Advise usage of terminating variable as above.




**Please make the changes and request a re-review for the given project**

If you get stuck somewhere, don't hesitate to reach out or schedule s 1:1 meeting with a Full-time TSE. 

Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

**Review by PhillipUg — CHANGES_REQUESTED** [review]
Hey team, 👋

You have done an amazing job implementing the requirements for this project.

However, there are still some changes 👇 you need to implement to approve this request 🔍

### Changes Required ♻️ 

- [x] You're supposed to actually implement that mock functionality instead of merely printing the instructions on the screen. So for instance, instead of printing out `game displays board after player move` you're supposed to actually print out the board after each player move. Those instructions are for you to implement not to print out on the screen.

#### Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack as **Phillip Musiime**
I would be happy to help! 👩‍💻 

Happy coding 🤓

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @udberg and @taiwo2  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [x] As it is stated in the previous review, you need to implement all of the requirements as they are stated:
> You're supposed to actually implement that mock functionality instead of merely printing the instructions on the screen. So for instance, instead of printing out game displays board after player move you're supposed to actually print out the board after each player move. Those instructions are for you to implement not to print out on the screen.

:x: Printing this: 
Screenshot from 2021-01-05 11-48-17
:point_right: That is not what the project is asking you to do, you are asked to implement those steps, not to print the sentences on the screen.

___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @taiwo2 and @udberg :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this milestone can be approved.

## REQUIRED

* [x] Basic game flow is prepared: ([screenshot hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
  * [x] `[OPTIONAL]` game asks players for their names
  * [x] `[REQUIRED]` game tells which player turn it is (without computing who the winner is)
     * [x] Since you want the players to enter **Horizontal position  with a letter** and also enter **Vertical position  with a number**, you should have specified that at the beginning of the game.
      * [x] The game didn't ask for the input of the second player. After I entered the vertical and horizontal positions for the first player, a full board was displayed.
  * [x] `[REQUIRED]` game asks the player to select from available moves
  * [x] `[REQUIRED]` game informs player if the selected move is invalid (without computing what an invalid move is)
  * [x] `[REQUIRED]` game displays board after the player move (without computing which spots on the board are taken)
  * [x] `[REQUIRED]` game informs player if the selected move is a winning move (without computing the winning move)
  * [x] `[REQUIRED]` game informs player if the selected move is a draw move (without computing draw)
  * [x] `[REQUIRED]` game repeats all actions for the next player's move



### Please, make the required changes and submit for another review.
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by taiwo2** [comment]
I don't really understand what you really want we did exactly as you commented, one of the TSE said we did wrong and you requested for the same changes which someone said need adjustment, I don't what is wrong? can we make a Zoom call with you cause we don't understand what you really want. this is content, not the real Logic Game. waiting for your response

**Review by mahmoud717 — APPROVED** [review]
### STATUS: APPROVED ✔️ ✔️ 

**Great job with making all of the requirements. the project is approved, you can go ahead and merge this pull request**

**Pull request merged**
