### PR TITLE
Milestone 3: Game logic.

### PR DESCRIPTION
**Pull request by udberg**
In this branch, we (@udberg and @taiwo2 ) created the logic for our tic-tac-toe game. We paid particular attention to the creation of different classes for different parts of the game logic and making sure to keep our code DRY.

### CODE REVIEW

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## :wave: :wave: Hello @udberg and @taiwo2. Thanks for submitting you project!

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [x] Please fix the branch issues that are mention on the PR related to the `bin/main.rb` file
- [x] Please remove unused files `.gitignore` is not being used, this applies to `.gitkeep`, this file is only used when trying to upload empty directories to a repository in GitHub.
- [x] In the `lib/board.rb` file accessor methods are being defined but not being called on the latter methods, please fix that. [LINK](https://launchschool.com/books/oo_ruby/read/classes_and_objects_part1#accessormethodsinaction)
- [x] There should be no `puts`/`prints` outside the `bin/main.rb` file, please check the files in `lib` directory and remove them.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Comment by descholar-ceo** [comment]
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: 
## Please wait a bit ...

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @udberg and @taiwo2  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is good, congratulations on the good work you have done so far.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
:warning: Your program has some bugs;
- [x] I was not able to run your game, because whenever I started it, it was throwing the following errors: 
Screenshot from 2021-01-05 23-33-41
Screenshot from 2021-01-05 23-42-37

- [x] I noticed that you've put all of the game logic in bin/main.rb file, hence that is not recommended, you should split your codes in different folders / files, the lib folder contains your game logic and the bin contains user interface of the game.
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @udberg and @taiwo2  :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this milestone can be approved.

## REQUIRED

* [x] No `puts/print` and `gets.chomp` outside `main.rb` file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
* [x] No inline comments left after the previous milestone. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/no_comment.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))



### Please, make the required changes and request for another review
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Review by jubaan — APPROVED** [review]
# :tada: :tada: :tada: :rotating_light: Status: Approved :rotating_light:  :tada: :tada: :tada:

#### :clap: :clap: Great job :hammer_and_pick:!! There are no more issues left to be addressed. 

## See you at the top :rocket:!

# :tada: :tada: :tada: :rotating_light: Status: Approved :rotating_light:  :tada: :tada: :tada:

**Pull request merged**
